#!/usr/bin/python3

from which_pyqt import PYQT_VER
if PYQT_VER == 'PYQT5':
	from PyQt5.QtCore import QLineF, QPointF
elif PYQT_VER == 'PYQT4':
	from PyQt4.QtCore import QLineF, QPointF
else:
	raise Exception('Unsupported Version of PyQt: {}'.format(PYQT_VER))




import time
import numpy as np
from TSPClasses import *
import heapq
import itertools



#create and return a cost matrix based on the cities O(n^2)
def createMatrix(cities):
	matrix = []
	for city in cities:
		row = []
		for neighbourCity in cities:
			cost = city.costTo(neighbourCity)
			row.append(cost)
		matrix.append(row)
	return matrix	


#reduces matrix O(n^2)
def reduceMatrix(matrix, lower, cost):
	cols = len(matrix[0])
	rows = len(matrix)

	for rows in range(rows):
			minimum = np.min(matrix[rows, :])
			if minimum == math.inf:
				continue
			lower += minimum
			matrix[rows, :] -= np.min(matrix[rows, :])


	for cols in range(cols):
		minimum = np.min(matrix[:, cols])
		if minimum == math.inf:
			continue
		lower += minimum
		matrix[:, cols] -= np.min(matrix[:, cols])

	

	lower += cost

	return matrix, lower 	


def childMatrix(matrix, bound, row, column, cost_):

	matrix[column][row] = math.inf
	matrix[row, :] = math.inf
	matrix[:, column] - math.inf 
	
	matrix, lower = reduceMatrix(matrix, lower, cost)

	return matrix, lower



class TSPSolver:
	def __init__( self, gui_view ):
		self._scenario = None

	def setupWithScenario( self, scenario ):
		self._scenario = scenario


	''' <summary>
		This is the entry point for the default solver
		which just finds a valid random tour.  Note this could be used to find your
		initial BSSF.
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of solution, 
		time spent to find solution, number of permutations tried during search, the 
		solution found, and three null values for fields not used for this 
		algorithm</returns> 
	'''
	
	def defaultRandomTour( self, time_allowance=60.0 ):
		results = {}
		cities = self._scenario.getCities()
		ncities = len(cities)
		foundTour = False
		count = 0
		bssf = None
		start_time = time.time()
		while not foundTour and time.time()-start_time < time_allowance:
			# create a random permutation
			perm = np.random.permutation( ncities )
			route = []
			# Now build the route using the random permutation
			for i in range( ncities ):
				route.append( cities[ perm[i] ] )
			bssf = TSPSolution(route)
			count += 1
			if bssf.cost < np.inf:
				# Found a valid route
				foundTour = True
		end_time = time.time()
		results['cost'] = bssf.cost if foundTour else math.inf
		results['time'] = end_time - start_time
		results['count'] = count
		results['soln'] = bssf
		results['max'] = None
		results['total'] = None
		results['pruned'] = None
		return results


	''' <summary>
		This is the entry point for the greedy solver, which you must implement for 
		the group project (but it is probably a good idea to just do it for the branch-and
		bound project as a way to get your feet wet).  Note this could be used to find your
		initial BSSF.
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of best solution, 
		time spent to find best solution, total number of solutions found, the best
		solution found, and three null values for fields not used for this 
		algorithm</returns> 
	'''

	def greedy( self,time_allowance=60.0 ):
		pass
	
	
	
	''' <summary>
		This is the entry point for the branch-and-bound algorithm that you will implement
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of best solution, 
		time spent to find best solution, total number solutions found during search (does
		not include the initial BSSF), the best solution found, and three more ints: 
		max queue size, total number of states created, and number of pruned states.</returns> 
	'''
		
	def branchAndBound( self, time_allowance=60.0 ):
		
		results = {}
		cities = self._scenario.getCities()
		numCities = len(cities)
		foundTour = False
		count = 0
		totalStates = 0
		maxQueue = 0
		numPruned = 0
		depth = 1
		visited = []
		initialTime = time.time()
		bssf = self.defaultRandomTour()['soln']

		priorityQueue = []
		heapq.heapify(priorityQueue)

		start_time = time.time()
		#begin populating our matrix's
		matrix = createMatrix(cities)
		matrix = np.asarray(matrix)

		#reduce our matrix to begin picking which path is best
		matrix, lower = reduceMatrix(matrix, 0, 0)
		cost = lower/depth
		#easy way for us to keep track
		matrixTuple = (cost, totalStates, lower, visited, matrix, depth)
		
		#debugging to see if everything is being printed correctly
		print(matrix)
		print(start_time)

		#keep track of our city and all the things that go along with it
		city = (cost, totalStates, lower, visited, matrix, depth)
		heapq.heappush(priorityQueue, city)
		

		#we are going to dive into our pathing by using this while loop
		#we can set it up so that as soon as we finish with our priority queue
		#finish checking up on all the other cities we will break from it
		#and then we will have our correct answer!
		while (len(priorityQueue) >= 1):		
			
			currCity = heapq.heapqpop(priorityQueue)
			currDepth = currCity[5]
			currMatrix = currCity[4]
			visitedCities = currCity[3]
			currLB = currCity[2]
			lastVisited = visitedCities[-1]

			#check if the bssf is lower than the currCities
			#LB, if not then we can move on
			if bssf.cost < currLB:
				#debugging
				print(bssf.cost)
				#We will check the different cities possible and
				#choose which route we will be taking
				for rows in range(rows):
					for cols in range(cols):
						currCity[cols]


			else:
				#debugging
				print(bssf.cost)
				continue	
	
		
		pass




		
		
		



	''' <summary>
		This is the entry point for the algorithm you'll write for your group project.
		</summary>
		<returns>results dictionary for GUI that contains three ints: cost of best solution, 
		time spent to find best solution, total number of solutions found during search, the 
		best solution found.  You may use the other three field however you like.
		algorithm</returns> 
	'''
		
	def fancy( self,time_allowance=60.0 ):
		pass
		



